import type { CapabilityDefinition } from "../types.js";

/**
 * APDR Capability Registry v2
 *
 * Naming: {layer}.{domain}.{action}.{variant}
 *   layer: atomic | composite
 *   domain: intake | research | analysis | spec | ux | visual | code | govern | diagram | eval
 *   variant: optional suffix for specificity
 */
export const CAPABILITY_REGISTRY: CapabilityDefinition[] = [
  // ─── Intake ────────────────────────────────────────────
  {
    id: "intake.parse.brief",
    layer: "atomic",
    domain: "intake",
    description: "Parse raw natural-language requirements into a structured ProjectBrief",
    inputs: ["raw_requirements", "constraints"],
    outputs: ["ProjectBrief"],
    sideEffects: "write_artifact",
    mcpTool: "start_project",
    humanGate: "optional",
    stage: "intake",
  },

  // ─── Analysis ──────────────────────────────────────────
  {
    id: "analysis.extract.requirements",
    layer: "composite",
    domain: "analysis",
    description: "Produce RequirementsAnalysis from ProjectBrief",
    inputs: ["ProjectBrief"],
    outputs: ["RequirementsAnalysis"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "required",
    stage: "requirements_analysis",
  },
  {
    id: "analysis.assumptions.validate",
    layer: "atomic",
    domain: "analysis",
    description: "Extract and flag risky assumptions from requirements analysis",
    inputs: ["RequirementsAnalysis"],
    outputs: ["assumption_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "requirements_analysis",
  },

  // ─── Spec / PRD ────────────────────────────────────────
  {
    id: "spec.prd.generate",
    layer: "composite",
    domain: "spec",
    description: "Generate PRD from approved requirements analysis",
    inputs: ["RequirementsAnalysis"],
    outputs: ["PRD"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "required",
    stage: "prd",
  },
  {
    id: "spec.prd.validate",
    layer: "atomic",
    domain: "spec",
    description: "Validate PRD completeness: features, acceptance criteria, successMetrics",
    inputs: ["PRD"],
    outputs: ["validation_report"],
    sideEffects: "read_artifact",
    mcpTool: null,
    humanGate: "none",
    stage: "prd",
  },
  {
    id: "spec.prd.export_markdown",
    layer: "atomic",
    domain: "spec",
    description: "Export PRD JSON to human-readable markdown for review or slide-deck input",
    inputs: ["PRD"],
    outputs: ["markdown_doc"],
    sideEffects: "write_artifact",
    mcpTool: null,
    humanGate: "none",
    stage: "prd",
  },
  {
    id: "spec.slide_deck.generate",
    layer: "atomic",
    domain: "spec",
    description: "Generate stakeholder slide deck outline from PRD markdown",
    inputs: ["PRD"],
    outputs: ["slide_deck"],
    sideEffects: "write_artifact",
    mcpTool: null,
    humanGate: "optional",
    stage: "prd",
  },

  // ─── UX: Flows ─────────────────────────────────────────
  {
    id: "ux.flow.render",
    layer: "composite",
    domain: "ux",
    description: "Generate user flows and Mermaid diagrams",
    inputs: ["PRD"],
    outputs: ["UserFlows"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "optional",
    stage: "user_flows",
  },
  {
    id: "ux.flow.render.diagram",
    layer: "atomic",
    domain: "ux",
    description: "Convert user-flow step list into a Mermaid flowchart diagram",
    inputs: ["UserFlows"],
    outputs: ["mermaid_string"],
    sideEffects: "none",
    mcpTool: "render_mermaid",
    humanGate: "none",
    stage: "user_flows",
  },
  {
    id: "ux.flow.validate_completeness",
    layer: "atomic",
    domain: "ux",
    description: "Check that every PRD feature has at least one corresponding user flow",
    inputs: ["PRD", "UserFlows"],
    outputs: ["coverage_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "user_flows",
  },

  // ─── UX: Information Architecture ──────────────────────
  {
    id: "ux.ia.generate",
    layer: "composite",
    domain: "ux",
    description: "Generate sitemap and navigation IA",
    inputs: ["PRD", "UserFlows"],
    outputs: ["InformationArchitecture"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "optional",
    stage: "information_architecture",
  },
  {
    id: "ux.ia.render.sitemap",
    layer: "atomic",
    domain: "ux",
    description: "Render IA sitemap tree into a structural diagram (Mermaid / SVG)",
    inputs: ["InformationArchitecture"],
    outputs: ["sitemap_diagram"],
    sideEffects: "none",
    mcpTool: "render_sitemap",
    humanGate: "none",
    stage: "information_architecture",
  },

  // ─── UX: Wireframes ────────────────────────────────────
  {
    id: "ux.wireframe.generate",
    layer: "composite",
    domain: "ux",
    description: "Generate low-fidelity wireframes (HTML) from IA and flows",
    inputs: ["InformationArchitecture", "UserFlows"],
    outputs: ["Wireframes"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "optional",
    stage: "wireframes",
  },
  {
    id: "ux.wireframe.render.html",
    layer: "atomic",
    domain: "ux",
    description: "Render a single wireframe page definition into an HTML file",
    inputs: ["WireframePage"],
    outputs: ["wireframe_html"],
    sideEffects: "write_artifact",
    mcpTool: null,
    humanGate: "none",
    stage: "wireframes",
  },
  {
    id: "ux.wireframe.preview.start",
    layer: "atomic",
    domain: "ux",
    description: "Start a local preview server for generated wireframe HTML files",
    inputs: ["project_id", "wireframe_dir"],
    outputs: ["preview_url"],
    sideEffects: "none",
    mcpTool: "serve_wireframe",
    humanGate: "none",
    stage: "wireframes",
  },

  // ─── Visual / UI Design ────────────────────────────────
  {
    id: "visual.token.infer",
    layer: "composite",
    domain: "visual",
    description: "Infer design tokens, component spec, and screen specs from wireframes",
    inputs: ["Wireframes", "brand_guidelines"],
    outputs: ["UIDesignSpec"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "required",
    stage: "ui_design",
  },
  {
    id: "visual.token.infer.color",
    layer: "atomic",
    domain: "visual",
    description: "Infer a color palette from brand description, constraints, or reference",
    inputs: ["brand_guidelines", "Wireframes"],
    outputs: ["color_tokens"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "ui_design",
  },
  {
    id: "visual.token.infer.typography",
    layer: "atomic",
    domain: "visual",
    description: "Infer typography system (headings, body, scale) from brand context",
    inputs: ["brand_guidelines"],
    outputs: ["typography_tokens"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "ui_design",
  },
  {
    id: "visual.token.infer.spacing",
    layer: "atomic",
    domain: "visual",
    description: "Infer spacing/rhythm system (margin, padding, gap scale) from wireframes",
    inputs: ["Wireframes"],
    outputs: ["spacing_tokens"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "ui_design",
  },
  {
    id: "visual.css.generate",
    layer: "atomic",
    domain: "visual",
    description: "Generate CSS custom properties from design tokens",
    inputs: ["UIDesignSpec"],
    outputs: ["css_variables"],
    sideEffects: "write_artifact",
    mcpTool: null,
    humanGate: "none",
    stage: "ui_design",
  },
  {
    id: "visual.concept.render",
    layer: "atomic",
    domain: "visual",
    description: "Generate a concept image for a key screen (via baoyu-imagine or DALL-E)",
    inputs: ["screen_descriptor", "Wireframes"],
    outputs: ["concept_image"],
    sideEffects: "write_artifact",
    mcpTool: null,
    humanGate: "optional",
    stage: "ui_design",
  },

  // ─── Code Generation ───────────────────────────────────
  {
    id: "code.react.page.generate",
    layer: "composite",
    domain: "code",
    description: "Scaffold React/Vite pages from approved UI design spec",
    inputs: ["UIDesignSpec"],
    outputs: ["CodeBundle"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "optional",
    stage: "frontend_codegen",
  },
  {
    id: "code.scaffold.react_vite",
    layer: "atomic",
    domain: "code",
    description: "Scaffold a React + Vite project from template into project app dir",
    inputs: ["project_id", "routes"],
    outputs: ["scaffold_path"],
    sideEffects: "write_artifact",
    mcpTool: "scaffold_frontend",
    humanGate: "none",
    stage: "frontend_codegen",
  },
  {
    id: "code.scaffold.html",
    layer: "atomic",
    domain: "code",
    description: "Scaffold a plain HTML/CSS/JS project from the HTML template",
    inputs: ["project_id", "pages"],
    outputs: ["scaffold_path"],
    sideEffects: "write_artifact",
    mcpTool: "scaffold_frontend",
    humanGate: "none",
    stage: "frontend_codegen",
  },
  {
    id: "code.preview.serve",
    layer: "atomic",
    domain: "code",
    description: "Start a local dev server for the generated frontend code",
    inputs: ["project_id", "stack", "app_dir"],
    outputs: ["preview_url"],
    sideEffects: "none",
    mcpTool: "serve_frontend",
    humanGate: "none",
    stage: "frontend_codegen",
  },
  {
    id: "code.quality.check",
    layer: "atomic",
    domain: "code",
    description: "Run static analysis or lint on generated code",
    inputs: ["code_dir"],
    outputs: ["lint_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "frontend_codegen",
  },

  // ─── Code Intelligence (CodeGraph) ─────────────────────
  {
    id: "code.intelligence.index",
    layer: "atomic",
    domain: "code",
    description: "Initialize or refresh CodeGraph index for projects/{id}/app/",
    inputs: ["project_id", "code_root"],
    outputs: ["index_path"],
    sideEffects: "none",
    mcpTool: "index_codebase",
    humanGate: "none",
    stage: "code_intelligence",
  },
  {
    id: "code.intelligence.analyze",
    layer: "composite",
    domain: "code",
    description:
      "Build CodeIntelligenceReport via CodeGraph: init, status, file tree, route/component exploration",
    inputs: ["CodeBundle"],
    outputs: ["CodeIntelligenceReport"],
    sideEffects: "write_artifact",
    mcpTool: "build_code_intelligence_report",
    humanGate: "optional",
    stage: "code_intelligence",
  },
  {
    id: "code.intelligence.explore",
    layer: "atomic",
    domain: "code",
    description: "Run codegraph explore against indexed project app directory",
    inputs: ["project_id", "query"],
    outputs: ["explore_result"],
    sideEffects: "none",
    mcpTool: "codegraph_explore",
    humanGate: "none",
    stage: "code_intelligence",
  },

  // ─── Research ──────────────────────────────────────────
  {
    id: "research.search.web",
    layer: "atomic",
    domain: "research",
    description: "Search the web for competitive intelligence or domain research",
    inputs: ["query"],
    outputs: ["search_results"],
    sideEffects: "none",
    mcpTool: "search_web",
    humanGate: "none",
  },
  {
    id: "research.fetch.url",
    layer: "atomic",
    domain: "research",
    description: "Fetch a URL and convert its content to clean markdown",
    inputs: ["url"],
    outputs: ["markdown_content"],
    sideEffects: "none",
    mcpTool: "fetch_url",
    humanGate: "none",
  },
  {
    id: "research.note.store",
    layer: "atomic",
    domain: "research",
    description: "Store a structured research note for a project under projects/{id}/research/",
    inputs: ["project_id", "query", "summary", "source_url"],
    outputs: ["research_note_path"],
    sideEffects: "write_artifact",
    mcpTool: "research_note",
    humanGate: "none",
  },

  // ─── Governance ────────────────────────────────────────
  {
    id: "govern.artifact.approve",
    layer: "atomic",
    domain: "govern",
    description: "Mark artifact as approved; marks downstream stages stale",
    inputs: ["artifact_id"],
    outputs: ["artifact_status"],
    sideEffects: "write_artifact",
    mcpTool: "approve_artifact",
    humanGate: "required",
  },
  {
    id: "govern.artifact.rollback",
    layer: "atomic",
    domain: "govern",
    description: "Set an approved artifact back to draft, resetting downstream gates",
    inputs: ["artifact_id"],
    outputs: ["artifact_status"],
    sideEffects: "write_artifact",
    mcpTool: "rollback_artifact",
    humanGate: "required",
  },
  {
    id: "govern.pipeline.rollback_stage",
    layer: "atomic",
    domain: "govern",
    description: "Roll the pipeline back to a previous stage, clearing downstream stale state",
    inputs: ["project_id", "target_stage"],
    outputs: ["pipeline_state"],
    sideEffects: "write_artifact",
    mcpTool: "rollback_pipeline",
    humanGate: "required",
  },
  {
    id: "govern.stale.list",
    layer: "atomic",
    domain: "govern",
    description: "List all artifacts that are stale due to upstream changes",
    inputs: ["project_id"],
    outputs: ["stale_list"],
    sideEffects: "read_artifact",
    mcpTool: "get_pipeline_status",
    humanGate: "none",
  },
  {
    id: "govern.artifact.list",
    layer: "atomic",
    domain: "govern",
    description: "List all artifacts for a project",
    inputs: ["project_id"],
    outputs: ["artifact_list"],
    sideEffects: "read_artifact",
    mcpTool: "list_artifacts",
    humanGate: "none",
  },

  // ─── Diagram / Visualization ───────────────────────────
  {
    id: "diagram.render.mermaid",
    layer: "atomic",
    domain: "diagram",
    description: "Render Mermaid markup into an SVG image",
    inputs: ["mermaid_markup"],
    outputs: ["svg_output"],
    sideEffects: "write_artifact",
    mcpTool: "render_mermaid",
    humanGate: "none",
  },
  {
    id: "diagram.render.sitemap",
    layer: "atomic",
    domain: "diagram",
    description: "Render an IA sitemap tree into a visual diagram",
    inputs: ["sitemap_tree"],
    outputs: ["svg_output"],
    sideEffects: "write_artifact",
    mcpTool: "render_sitemap",
    humanGate: "none",
  },

  // ─── Evaluation ────────────────────────────────────────
  // ─── Design Review ─────────────────────────────────
  {
    id: "review.design.full",
    layer: "composite",
    domain: "review",
    description: "Full design quality review: token consistency, components, responsive, accessibility",
    inputs: ["UIDesignSpec", "Wireframes"],
    outputs: ["DesignReviewReport"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "required",
    stage: "design_review",
  },
  {
    id: "review.design.consistency",
    layer: "atomic",
    domain: "review",
    description: "Check token and component consistency across UIDesignSpec",
    inputs: ["UIDesignSpec"],
    outputs: ["consistency_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "design_review",
  },
  {
    id: "review.design.accessibility",
    layer: "atomic",
    domain: "review",
    description: "Check WCAG compliance: contrast, focus, labels, semantics",
    inputs: ["UIDesignSpec", "Wireframes"],
    outputs: ["a11y_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
    stage: "design_review",
  },
  {
    id: "doc.handoff.generate",
    layer: "composite",
    domain: "doc",
    description: "Generate developer handoff documentation with component docs, routes, tokens, build instructions",
    inputs: ["CodeBundle", "UIDesignSpec", "PRD"],
    outputs: ["HandoffDoc"],
    sideEffects: "write_artifact",
    mcpTool: "write_artifact",
    humanGate: "optional",
    stage: "handoff",
  },
  {
    id: "eval.artifact.quality",
    layer: "atomic",
    domain: "eval",
    description: "Run a quality/rubric check on any artifact type",
    inputs: ["artifact_envelope", "rubric"],
    outputs: ["quality_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
  },
  {
    id: "eval.coverage.feature_flow",
    layer: "atomic",
    domain: "eval",
    description: "Verify every PRD feature has corresponding flows and wireframe screens",
    inputs: ["PRD", "UserFlows", "Wireframes"],
    outputs: ["coverage_gap_report"],
    sideEffects: "none",
    mcpTool: null,
    humanGate: "none",
  },
];

export function getCapability(id: string): CapabilityDefinition | undefined {
  return CAPABILITY_REGISTRY.find((c) => c.id === id);
}

export function capabilitiesForStage(stage: string): CapabilityDefinition[] {
  return CAPABILITY_REGISTRY.filter((c) => c.stage === stage);
}

export function capabilitiesByDomain(domain: string): CapabilityDefinition[] {
  return CAPABILITY_REGISTRY.filter((c) => c.domain === domain);
}

export function atomicCapabilities(): CapabilityDefinition[] {
  return CAPABILITY_REGISTRY.filter((c) => c.layer === "atomic");
}

export function compositeCapabilities(): CapabilityDefinition[] {
  return CAPABILITY_REGISTRY.filter((c) => c.layer === "composite");
}
